on: ["push", "pull_request"]

name: Test Coveralls

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install dependencies and run tests with coverage
        run: |
          npm install
          npm run test

      - name: Submit coverage to Coveralls
        if: success() || failure()
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel: true

  finish:
    needs: test
    if: success() || failure()
    runs-on: ubuntu-latest
    steps:
      - name: Finalize Coveralls Parallel
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true
