on: ["push", "pull_request"]

name: Test Coveralls

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: npm install and run tests with coverage
        run: |
          npm install
          npm run test

      - name: Coveralls
        uses: coverallsapp/github-action@v2
        env:
          github-token: ${{ secrets.GITHUB_TOKEN }}
